- name: Example loops range cycle
  hosts: deb11test
  gather_facts: 'no'
  become: 'yes'
  vars:
    file_path: '/opt'
    project_title: 'service_1'
    current_dir: '/opt/{{ project_title }}/current'

  tasks:
  - name: Create tests files for ports 3000-3019
    file:
      path: '{{ file_path }}/{{ project_title }}_{{ item }}.service'
      state: touch
      owner: root
      group: root
      mode: '0644'
    loop: '{{ range(3000,3020) }}'

  - name: Configuration systemd file for ports 3000-3019
    copy:
      content: |
        [Unit]
        Description={{ project_title }}_{{ item }}
        After=multi-user.target

        [Service]
        Type=idle
        WorkingDirectory={{ current_dir }}
        ExecStart={{ current_dir }}/{{ project_title }} {{ item }}
        SyslogIdentifier={{ project_title }}_{{ item }}
        Restart=always
        RestartSec=60

        [Install]
        WantedBy=multi-user.target
      dest: '{{ file_path }}/{{ project_title }}_{{ item }}.service'
    loop: '{{ range(3000,3020) }}'
### tets example playbook ###